<?php
/**
 * CSS to PHP Array Map
 * ==========================================
 * Generated by CSS2PHP Converter v1.0.1
 * Created by @sakibweb
 * https://github.com/sakibweb/css2php
 * ==========================================
 *
 * Source Information:
 * ------------------------------------------
 * File: https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/components.min.css
 * Generated: 2025-03-16 02:03:36
 *
 * Processing Statistics (A-Z):
 * ------------------------------------------
 * Classes found: 36
 * Compression ratio: 173.4%
 * Input size: 2,029 bytes
 * Media queries: 35
 * Output size: 3,518 bytes
 * Processing time: 1742069016.192s
 * Pseudo-classes: 30
 * Syntax validation: ✅ Valid
 *
 * Configuration:
 * ------------------------------------------
 * Parse mode: Advanced (cssutils)
 * Skip errors: Yes
 * Timeout: 30s
 * Overwrite enabled: Yes
 * Split Selectors: No
 *
 * File Structure:
 * ------------------------------------------
 * - Array keys are CSS class selectors.
 * - Combined selectors are kept as single keys
 * - Each key represents a CSS selector and its associated styles.
 * - Each class selector has 'default' and optional 'media' properties.
 * - Media queries are nested under 'media' key.
 * - All properties are sorted alphabetically.
 * ==========================================
 */

return [
    '2xl:container' => [
        'media' => [
            '(min-width: 1024px)' => 'max-width: 1024px;',
            '(min-width: 1280px)' => 'max-width: 1280px;',
            '(min-width: 1536px)' => 'max-width: 1536px;',
            '(min-width: 640px)' => 'max-width: 640px;',
            '(min-width: 768px)' => 'max-width: 768px;',
        ],
    ],
    'container' => [
        'default' => 'width: 100%;',
        'media' => [
            '(min-width: 1024px)' => 'max-width: 1024px;',
            '(min-width: 1280px)' => 'max-width: 1280px;',
            '(min-width: 1536px)' => 'max-width: 1536px;',
            '(min-width: 640px)' => 'max-width: 640px;',
            '(min-width: 768px)' => 'max-width: 768px;',
        ],
    ],
    'lg:container' => [
        'media' => [
            '(min-width: 1024px)' => 'max-width: 1024px;',
            '(min-width: 1280px)' => 'max-width: 1280px;',
            '(min-width: 1536px)' => 'max-width: 1536px;',
            '(min-width: 640px)' => 'max-width: 640px;',
            '(min-width: 768px)' => 'max-width: 768px;',
        ],
    ],
    'md:container' => [
        'media' => [
            '(min-width: 1024px)' => 'max-width: 1024px;',
            '(min-width: 1280px)' => 'max-width: 1280px;',
            '(min-width: 1536px)' => 'max-width: 1536px;',
            '(min-width: 640px)' => 'max-width: 640px;',
            '(min-width: 768px)' => 'max-width: 768px;',
        ],
    ],
    'sm:container' => [
        'media' => [
            '(min-width: 1024px)' => 'max-width: 1024px;',
            '(min-width: 1280px)' => 'max-width: 1280px;',
            '(min-width: 1536px)' => 'max-width: 1536px;',
            '(min-width: 640px)' => 'max-width: 640px;',
            '(min-width: 768px)' => 'max-width: 768px;',
        ],
    ],
    'xl:container' => [
        'media' => [
            '(min-width: 1024px)' => 'max-width: 1024px;',
            '(min-width: 1280px)' => 'max-width: 1280px;',
            '(min-width: 1536px)' => 'max-width: 1536px;',
            '(min-width: 640px)' => 'max-width: 640px;',
            '(min-width: 768px)' => 'max-width: 768px;',
        ],
    ],
];
